### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by joprice-chainalysis** [grimoh/asdf-terraformer#6]
When trying to install terraformer using the plugin, I get the error below. It seems that the `download` file does not have executable flag set.

```bash
asdf install terraformer 0.8.19
/home/.asdf/lib/commands/command-install.bash: line 203: /home/.asdf/plugins/terraformer/bin/download: Permission denied
```

**Comment by grimoh** [comment]
Thanks.
This issue was resolved by #7 .
